# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "/:title/"

highlighter: rouge

timezone: Europe/Helsinki

# Default YAML frontmatter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Facebook settings
fb_admins:          606660677
avatar:             "/public/images/me_hires.png"
locale:             en_US

# Image settings
image_base:          /public/images/

# Do not copy these file to the output directory
exclude: ["transfer.sh", README.md]

#fb_appid:           337414769782635

# Setup
title:               Del Bao
tagline:             Sapere aude!
url:                 ""
paginate_l:           4
baseurl:             ""

paginate_langs:      ["en"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Del Bao
  url:               https://twitter.com/vitalyrepin
  email:             vitaly_repin@fsfe.org

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/delbao

# Google sitemap generation
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Conversion
# markdown:    redcarpet
excerpt_separator: "<!--break-->"

redcarpet:
  extensions: ["footnotes"]

kramdown:
  auto_ids: true

pages_list:
  About: '/about/'
  Hobby projects: '/hobbies/'
  Tags: '/tags/'
  Feed: '/atom.xml'

picture:
  source: "_assets/imgs/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      source_medium:
        media: "(min-width: 40em)"
        width: "640"
      source_small:
        height: "100"
      source_default:
        width: "640"
